// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljanfidwqhytjtqnhwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqYW5maWR3cWh5dGp0cW5od3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjI0NTcsImV4cCI6MjA1NzU5ODQ1N30.qeUMM6qy90Zj_yvC4Ho90mhrJdp0wK70Cqfw6jJsS5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);